package com.rule;
import com.mypack.binding.PlanInfo;
import com.mypack.binding.IndvInfo;

rule "SNAP Plan Rules For Approved"


	when 
		indvInfo:IndvInfo(isEmployed=="N")
	then
	PlanInfo planInfo=new PlanInfo();
	
	planInfo.setPlanName("SNAP");
	planInfo.setPlanStatus("Approved");
	planInfo.setPlanStartDate("04-10-2021");
	planInfo.setPlanEndDate("04-10-2022");
	planInfo.setBenefitAmmount("3000INR");
	indvInfo.setPlanInfo(planInfo);
	end
	
rule "SNAP Plan Rules For Denied"
	when 
			indvInfo:IndvInfo(isEmployed=="Y")
	then
		PlanInfo planInfo=new PlanInfo();
	planInfo.setPlanName("SNAP");
	planInfo.setPlanStatus("Denied");
	planInfo.setDenialReason("High Income");
	indvInfo.setPlanInfo(planInfo);
	end
	